sudo: required
dist: xenial
language: python
install:
  - sudo apt-get install libav-tools -y
  - pip3 install -r requirements.txt
  - pip3 install tox
  - python setup.py develop
  - avconv -version
  - avconv -help
python:
  - "3.6"
script:
  - tox
  - cd example && prosopopee
notifications:
  irc: "chat.freenode.net#prosopopee"
