sudo: required
dist: xenial
language: python
install:
  - sudo apt-get install libav-tools -y
  - pip3 install -r requirements.txt
  - python setup.py develop
python:
  - "3.6"
script:
  - cd example && prosopopee build
notifications:
  irc: "chat.freenode.net#prosopopee"
