#!/usr/bin/env python

import os
import sys
import yaml


def main():
    if not os.path.exists(os.path.join(os.getcwd(), "settings.yaml")):
        sys.stderr.write("I can't find a settings.yaml, abort\n")
        sys.exit(1)

    settings = yaml.safe_load("settings.yaml")

    if not os.path.exists("build"):
        os.makedirs("build")


if __name__ == '__main__':
    main()
